server:
  port: 9030

spring:
  application:
    name: fifaspid
  pid:
    file: /data1/api/fifaspid.pid
  data:
    mongodb:
      host: 43.201.236.116
      port: 27017
      database: DB_TIER_FIFA
      authentication-database: admin 
      username: admin
      password: dkssud13
      
logging:
  config: classpath:logback-local.xml
  
springdoc:
  swagger-ui:
    path: /doc/swagger
    operations-sorter: method


