server:
  port: 9000

spring:
  application:
    name: fifausers
  pid:
    file: /data1/api/fifausers.pid
  data:
    mongodb:
      host: ec2-13-209-40-73.ap-northeast-2.compute.amazonaws.com
      port: 27017
      database: DB_TIER_FIFA
      authentication-database: admin 
      username: admin
      password: dkssud13
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://192.168.0.102:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: foresys#@1      
logging:
  config: classpath:logback-local.xml
  
springdoc:
  swagger-ui:
    path: /doc/swagger
    operations-sorter: method


